### ISSUE TITLE
Does not work on current versions of Xposed/Android

### ISSUE THREAD

**Issue by Natanji** [Skarafaz/NetworkMonitoredBlocker#4]
I've tried to get this working on Android 5.1.1 (actually, CyanogenOS 12.1 on stock OnePlus One up to date ROM) and the message still appears. Xposed is version 75.

**Comment by Skarafaz** [comment]
https://github.com/Skarafaz/NetworkMonitoredBlocker/issues/2

**Comment by YtvwlD** [comment]
~~ Um, the alert was introduced in KitKat, but it still exists in recent versions of Android.
It would be nice, if one could get rid of it, there, too. ~~
Edit: #2 Sorry.
